openapi: "3.0.2"
info:
  title: "GoogleSheet Integration API for AuditorPro"
  description: "Create Google sheet and add questons row, answers row and row of user data every user which answer questons to there."
  version: '1'
  termsOfService: "http://localhost:9002/v1/googlesheet/"
  contact:
    name: "Pavel Popov"
    email: "popovpp@yandex.ru"
servers:
- url: http://localhost:9002
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - ApiKeyAuth: []
tags:
  - name: OPERATIONS
paths:
  /v1/googlesheet/googlesheetintegration/:
    get:
      tags:
      - OPERATIONS
      summary: Get list of all valid GS integrations
      operationId: GetListGHI
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                      description: Url of object GoogleSheetIntegration
                    id:
                      type: integer
                      description: Id of object GoogleSheetIntegration
                    user:
                      type: object
                      description: User id
                      properties:
                        id:
                          type: integer
                    poll_id:
                      type: integer
                      description: Poll id
                    is_active:
                      type: boolean
                      description: Flag of activity of integration
                    spreadsheet_url:
                      type: string
                      description: Url of google sheet to there will write user's data
                    row_count: 
                      type: integer
                      description: Counter of rows of 
                    survey_id:
                      type: array
                      description: List of survey_ids
                      items:
                        type: integer
        401:
          description: Unauthorized error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        403:
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
    post:
      tags:
      - OPERATIONS
      summary: Create GS integration object
      operationId: CreateGHI
      requestBody:
        description: You need to transmit poll_id
        content: 
          'application/json':
            schema:
              type: object
              properties:
                poll_id:
                  type: integer
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                      description: Url of object GoogleSheetIntegration
                    id:
                      type: integer
                      description: Id of object GoogleSheetIntegration
                    uuser:
                      type: object
                      description: User id
                      properties:
                        id:
                          type: integer
                    poll_id:
                      type: integer
                      description: Poll id
                    is_active:
                      type: boolean
                      description: Flag of activity of integration
                    spreadsheet_url:
                      type: string
                      description: Url of google sheet to there will write user's data
                    row_count: 
                      type: integer
                      description: Counter of rows of 
                    survey_id:
                      type: array
                      description: srrwerwer
                      items:
                        type: integer
        400:
          description: Error - bad request by uncorrect "poll_id"
          content:
            application/json:
              schema:
                type: object
                properties:
                  poll_id:
                    type: array
                    items:
                      type: string
        401:
          description: Unauthorized error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        403:
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
  /v1/googlesheet/googlesheetintegration/{id}/:
    get:
      tags:
      - OPERATIONS
      summary: Get GS integrations object has id
      operationId: GetGHIObject
      parameters:
      - name: id
        in: path
        required: true
        description: 'GS integration id'
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    url:
                      type: string
                      description: Url of object GoogleSheetIntegration
                    id:
                      type: integer
                      description: Id of object GoogleSheetIntegration
                    user:
                      type: object
                      description: User id
                      properties:
                        id:
                          type: integer
                    poll_id:
                      type: integer
                      description: Poll id
                    is_active:
                      type: boolean
                      description: Flag of activity of integration
                    spreadsheet_url:
                      type: string
                      description: Url of google sheet to there will write user's data
                    row_count: 
                      type: integer
                      description: Counter of rows of 
                    survey_id:
                      type: array
                      description: srrwerwer
                      items:
                        type: integer
        401:
          description: Unauthorized error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        403:
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        404:
          description: Not found error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
    put:
      tags:
      - OPERATIONS
      summary: Write user answers when survey is ended to Google sheet which made by POST
      operationId: WriteUserAnswers
      requestBody:
        description: You need to transmit poll_id and survey_id
        content: 
          'application/json':
            schema:
              type: object
              properties:
                poll_id:
                  type: integer
                survey_id:
                  type: array
                  items:
                    type: integer
      parameters:
      - name: id
        in: path
        required: true
        description: 'GS integration id'
        schema:
          type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    url:
                      type: string
                      description: Url of object GoogleSheetIntegration
                    id:
                      type: integer
                      description: Id of object GoogleSheetIntegration
                    user:
                      type: object
                      description: User id
                      properties:
                        id:
                          type: integer
                    poll_id:
                      type: integer
                      description: Poll id
                    is_active:
                      type: boolean
                      description: Flag of activity of integration
                    spreadsheet_url:
                      type: string
                      description: Url of google sheet to there will write user's data
                    row_count: 
                      type: integer
                      description: Counter of rows of 
                    survey_id:
                      type: array
                      description: srrwerwer
                      items:
                        type: integer
        401:
          description: Unauthorized error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        400:
          description: Error - bad request by uncorrect "poll_id" or "survey_id". "poll_id" and "survey_id" are named "key_name" togather.
          content:
            application/json:
              schema:
                type: object
                properties:
                  key_name:
                    type: array
                    items:
                      type: string
        403:
          description: Authentication error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
        404:
          description: Not found error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    description: Message about error
